### ISSUE TITLE
[Question] What do the rest of the cables do?

### ISSUE THREAD

**Issue by sanchosk** [ahermann86/LX79x_WiFi#4]
First of all, AMAZING project - I'll be building it this weekend or latest the next one. Thanks, I always wanted my lawnmower to be wifi without the chinese registration site.
I wonder if you have any idea what the rest of the cables in the 14pin connector are?

**Comment by ahermann86** [comment]
I'm glad to read that. My ambition is to be cloud-free as far as possible ;)

I assume that the lines (LCL LAD LBK LRS LSD LCS) are signals for the gyroscope.
